version: '2.1'
orbs:
  dastardly: portswigger/dastardly
jobs:
  scan-with-test-results:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - dastardly/scan:
          output_filename: scan_report1.xml
          target_url: https://portswigger-labs.net
      - store_test_results:
          path: scan_report1.xml
workflows:
  use-my-orb:
    jobs:
      - scan-with-test-results
