version: '2.1'
orbs:
  burp-suite-enterprise: portswigger/burp-suite-enterprise@0.1.3
jobs:
  scan-with-test-results:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - burp-suite-enterprise/scan:
          enterprise_api_key: 7dc16dc910667cf0b857ffe554e4be3b
          enterprise_server_url: https://2071b7b4.portswigger.cloud
          start_url: https://portswigger-labs.net
      - store_test_results:
          path: burp_junit_report.xml
workflows:
  use-my-orb:
    jobs:
      - scan-with-test-results
